name: Publish package to GitHub Packages

on:
  push:
    branches:
      - 'release'
  release:
    types: [created] 

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      repository-projects: write
      packages: write
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          settings-path: ${{ github.workspace }}
            
      - name: Maven Release x GitHub Packages
        run: |
          git config --global user.name "Genkey build bot"
          git config --global user.email "build@genkey.com"
          mvn release:prepare --batch-mode 
          mvn release:perform -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
