name: Publish package to GitHub Packages

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/release.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release the code
        if: "github.ref_name == 'release-branch' && !contains(github.event.head_commit.message, '[ci skip]')"
        uses: qcastel/github-actions-maven-release@master
        env:
          JAVA_HOME: /usr/lib/jvm/java-21-openjdk/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release-branch-name: "release"
          maven-servers: |
            [{
                "id": "github",
                "username": "${{ secrets.RELEASE_USER }}",
                "password": "${{ secrets.RELEASES_PWD }}"
            }]
            
      - name: Maven Release x GitHub Packages
        if: "github.ref_name == 'release' && !contains(github.event.head_commit.message, '[ci skip]')"
        run: |
          git config --global user.name "Genkey build bot"
          git config --global user.email "build@genkey.com"
          mvn release:prepare --batch-mode 
          mvn release:perform -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
